modLoader="javafml"
loaderVersion="[2,)"
license="Apache License version 2.0"

[[mods]]
modId="boringmod"
version="1.0.0"
displayName="Boring Mod"
displayURL="https://github.com/Spicy-Steve/boringmod"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="SpicySteve"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.boringmod]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.boringmod]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"



